services:
  - type: web
    name: proxy-rt-api
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install --with-deps chromium
    startCommand: uvicorn proxy_RT:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
